name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
        dotnetVersion: [6.0.x 8.0.x]
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
      - name: ✨ Setup .NET ${{ matrix.dotnetVersion }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnetVersion }}
      - name: Display Dotnet Versio  n
        run: dotnet --version
      - name: 🚚 Restore
        run: dotnet restore src
      - name: 🛠️ Build
        run: dotnet build src --configuration Release --no-restore
      - name: 🧪 Test
        run: dotnet test src --configuration Release --no-build
