name: Package

on:
  workflow_dispatch:

jobs:
  build:
    name: Package and Deploy
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
      - name: ✨ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          dotnet-quality: "preview"
      - name: 🚚 Restore
        run: dotnet restore src
      - name: 🛠️ Build
        run: dotnet build src
      - name: 🧪 Test
        run: dotnet test src
      - name: 📦 Pack
        run: dotnet pack src
      - name: 🔑 Secret
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      - name: 🚀 Deploy
        run: nuget push "src\FftSharp\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json